# frozen_string_literal: true

module Engine
  module Game
    module G18ESP
      module Entities
        MINE_HEXES = %w[D5 D9 F9 F19 F11 H9 I6 J7 D23 H21 E32 F31 I30 J23 E8 E18 F7 C30 G30 G32 J21].freeze

        COMPANIES = [
          {
            sym: 'P1',
            name: 'Ferrocarril de La Habana a Güines',
            value: 50,
            revenue: 20,
            min_price: 1,
            desc: 'No special abilities.',
            color: nil,
          },
          {
            sym: 'P2',
            name: 'Ferrocarril de Barcelona a Mataró',
            value: 5,
            revenue: 5,
            min_price: 1,
            desc: 'Owning Corporation receives 2 train. The train can not run in the same OR this company is purchased. '\
                  'Closes when 2 train runs. Purchased for winning bid value',
            color: nil,
          },
          {
            sym: 'P3',
            name: 'Ferrocarril de Madrid a Aranjuez o El tren de la fresa',
            value: 70,
            revenue: 15,
            min_price: 1,
            desc: 'Owning Corporation may place a Strawberry token in Aranjuez (town connected to madrid)' \
                  'to add 20 to all routes it runs to this location',
            color: nil,
            abilities: [{
              type: 'assign_hexes',
              when: 'owning_corp_or_turn',
              hexes: %w[G26],
              count: 1,
              owner_type: 'corporation',
            },
                        {
                          type: 'assign_corporation',
                          when: 'sold',
                          count: 1,
                          owner_type: 'corporation',
                        }],
          },
          {
            sym: 'P4',
            name: 'Ferrocarril de Valencia a Játiva',
            value: 100,
            revenue: 15,
            min_price: 1,
            desc: 'Owning corporation can upgrade one train per OR and attach a luxury carriage. '\
                  "Luxury carriages provide one more town to the train's range. "\
                  'Can only be attached to iberian gauge trains. ',
            abilities: [
                      {
                        type: 'base',
                        owner_type: 'corporation',
                        description: 'Luxury Carriage',
                        desc_detail: 'Private allows to attach Luxury crriage to regular trains '\
                                     'extending their distance by one town.',
                        when: 'owning_corp_or_turn',
                      },
                    ],
            color: nil,
          },
          {
            sym: 'P5',
            name: 'Ferrocarril de Alar del Rey a Santander',
            value: 160,
            revenue: 15,
            min_price: 1,
            desc: '20 discount on Alar del Rey mountain pass',
            color: nil,
          },
          {
            sym: 'P6',
            name: 'Ferrocarril de Carreño',
            value: 180,
            revenue: 30,
            desc: 'President share of one Northern major company (randomly selected before the game starts).'\
                  'It closes when the major company buys its first train.',
            color: nil,
            abilities: [{ type: 'shares', shares: 'random_president' }, { type: 'no_buy' }],
          },
          sym: 'MEA',
          name: 'Mining Exploitation Authorization',
          value: 30,
          revenue: 0,
          desc: 'Lay tile on a mine Hex. Must be used in the same OR it was purchased. Turns into a 2 freight train',
          abilities: [
            {
              type: 'tile_lay',
              owner_type: 'corporation',
              when: 'track',
              count_per_or: 1,
              free: true,
              special: false,
              reachable: true,
              closed_when_used_up: true,
              hexes: MINE_HEXES,
              tiles: [],
            },
            { type: 'blocks_hexes', owner_type: :player, hexes: MINE_HEXES },
          ],
        ].freeze

        # corporations with different properties in 1st Edition
        CORPORATIONS = [
          {
            float_percent: 40,
            sym: 'N',
            name: 'Compañía de los Caminos de Hierro del Norte de España',
            logo: '18_esp/N',
            coordinates: 'G24',
            city: 1,
            max_ownership_percent: 60,
            tokens: [0, 50, 50, 50, 50, 100],
            color: '#C29137',
            type: 'major',
            destination: 'F21',
          },
          {
            float_percent: 40,
            sym: 'MZA',
            name: 'Compañía de los ferrocarriles de Madrid a Zaragoza y Alicante ',
            logo: '18_esp/MZA',
            coordinates: 'G24',
            city: 2,
            max_ownership_percent: 60,
            tokens: [0, 50, 50, 50, 50, 100],
            color: '#FFD526',
            type: 'major',
            destination: 'K28',
          },
          {
            float_percent: 40,
            sym: 'A',
            name: 'Compañía de los Ferrocarriles Andaluces',
            logo: '18_esp/A',
            coordinates: 'F33',
            max_ownership_percent: 60,
            tokens: [0, 50, 50, 50, 50, 100],
            color: '#B75835',
            type: 'major',
            destination: 'D31',
          },
          {
            float_percent: 40,
            sym: 'CRB',
            name: 'Compañía de los Caminos de Hierro de Ciudad Real a Badajoz',
            logo: '18_esp/CRB',
            coordinates: 'C26',
            max_ownership_percent: 60,
            tokens: [0, 50, 50, 50, 50, 100],
            color: '#E96B28',
            type: 'major',
            destination: 'G28',
          },
          {
            float_percent: 40,
            sym: 'MCP',
            name: 'Compañía de los ferrocarriles de Madrid a Cáceres y Portugal',
            logo: '18_esp/MCP',
            coordinates: 'G24',
            city: 0,
            max_ownership_percent: 60,
            tokens: [0, 50, 50, 50, 50, 100],
            color: '#009AD5',
            type: 'major',
            destination: 'D25',
          },

          {
            float_percent: 40,
            sym: 'ZPB',
            name: 'Compañía de los Ferrocarriles de Zaragoza a Pamplona y
            Barcelona',
            logo: '18_esp/ZPB',
            coordinates: 'N21',
            max_ownership_percent: 60,
            tokens: [0, 50, 50, 50, 50, 100],
            color: '#DA0A26',
            type: 'major',
            destination: 'K20',
          },

          {
            float_percent: 40,
            sym: 'FdSB',
            name: 'Ferrocarril de Santander a Bilbao',
            logo: '18_esp/FdSB',
            coordinates: 'J5',
            max_ownership_percent: 60,
            tokens: [0, 50, 50, 50, 50],
            color: '#009AD5',
            type: 'major',
            destination: 'L5',
          },

          {
            float_percent: 40,
            sym: 'CFEA',
            name: 'Compañía de los Ferrocarriles Económicos de Asturias',
            logo: '18_esp/CFEA',
            coordinates: 'E6',
            max_ownership_percent: 60,
            tokens: [0, 50, 50, 50, 50],
            color: '#E96B28',
            type: 'major',
            destination: 'H5',
          },

          {
            float_percent: 40,
            sym: 'CFLG',
            name: 'Compañía del Ferrocarril de Langreo en Asturias',
            logo: '18_esp/CFLG',
            coordinates: 'F3',
            max_ownership_percent: 60,
            tokens: [0, 50, 50, 50, 50],
            color: '#DA0A26',
            type: 'major',
            destination: 'F7',
          },

          {
            float_percent: 40,
            sym: 'FdLR',
            name: 'Ferrocarril de La Robla',
            logo: '18_esp/FdLR',
            coordinates: 'I8',
            max_ownership_percent: 60,
            tokens: [0, 50, 50, 50, 50],
            color: '#009141',
            type: 'major',
            destination: 'L5',
          },

          {
            sym: 'MS',
            name: 'Ferrocarril de Mérida a Sevilla',
            logo: '18_esp/MS',
            coordinates: 'D27',
            color: '#7DCCE5',
            tokens: [0],
            type: 'minor',
            shares: [50, 25, 25],
            float_percent: 50,
            max_ownership_percent: 75,
            startable: true,
            destination: 'D31',
          },
          {
            sym: 'CM',
            name: 'Compañía del Ferrocarril de Córdoba a Málaga',
            logo: '18_esp/CM',
            coordinates: 'F29',
            color: '#009141',
            tokens: [0],
            type: 'minor',
            shares: [50, 25, 25],
            float_percent: 50,
            max_ownership_percent: 75,
            startable: true,
            destination: 'F33',
          },
          {
            sym: 'SC',
            name: 'Compañía del Ferrocarril de Sevilla a Jerez y de Puerto Real a Cádiz',
            logo: '18_esp/SC',
            simple_logo: '18_esp/SC',
            coordinates: 'D31',
            color: '#FFF014',
            tokens: [0],
            type: 'minor',
            shares: [50, 25, 25],
            float_percent: 50,
            max_ownership_percent: 75,
            startable: true,
            destination: 'D33',
          },
          {
            sym: 'AC',
            name: 'Ferrocarril de Albacete a Cartagena',
            logo: '18_esp/AC',
            coordinates: 'I28',
            color: '#B75835',
            tokens: [0],
            type: 'minor',
            shares: [50, 25, 25],
            float_percent: 50,
            max_ownership_percent: 75,
            startable: true,
            destination: 'K30',
          },
          {
            sym: 'MZ',
            name: 'Ferrocarril de Madrid a Zaragoza',
            logo: '18_esp/MZ',
            coordinates: 'G24',
            city: 2,
            color: '#7E7F7E',
            tokens: [0],
            type: 'minor',
            shares: [50, 25, 25],
            float_percent: 50,
            max_ownership_percent: 75,
            startable: true,
            destination: 'K20',
            abilities: [{ type: 'token', hexes: ['G24'], cheater: true, when: 'track', price: 0 }],
          },
          {
            sym: 'ZP',
            name: 'Compañía del Ferrocarril de Zaragoza a Pamplona',
            logo: '18_esp/ZP',
            coordinates: 'K20',
            color: '#D90072',
            tokens: [0],
            type: 'minor',
            shares: [50, 25, 25],
            float_percent: 50,
            max_ownership_percent: 75,
            startable: true,
            destination: 'N21',
          },
        ].freeze
      end
    end
  end
end
